### ISSUE TITLE
Class 'Laralum\Laralum\LaralumServiceProvider' not found

### ISSUE THREAD

**Issue by crmolinaz** [Laralum/Laralum#10]
Hi, i just give a try to see how it is, but i found this error: Class 'Laralum\Laralum\LaralumServiceProvider' not found 

i follow the documentation, am i missing something?

**Comment by 24aitor** [comment]
Please read carefully [documentation](https://laralum.com/docs/Introduction/Installation). It's explained how to register the service provider.

**Comment by crmolinaz** [comment]
in this part?

Register the service provider

Register the laralum service provider to load laralum components and auto register other laralum service providers.

To register service provider add the next code snippet to providers array of config\app.php

Laralum\Laralum\LaralumServiceProvider::class,

or exists something else to worry about?

**Comment by crmolinaz** [comment]
i will close the issue, i didn't found the solution in your documentation, so i just move on. Thanks.

**Comment by 24aitor** [comment]
No, only register Laralum\Laralum\LaralumServiceProvider::class, and continue steps of installation docs.

**Comment by ConsoleTVs** [comment]
@crmolinaz You need to download the cms first:

```
composer require laralum/laralum
```

Then, the service provider needa to be added inside the "providers" array. Can you screenshot me the config/app.php where you added the line? Can you screenshot me ```/vendor/laralum``` folder? Thanks.
