### ISSUE TITLE
Login in to Admin

### ISSUE THREAD

**Issue by onubrooks** [Laralum/Laralum#12]
i am currently unable to login to the admin panel despite entering the right credentials repeatedly. It always returns "credentials do not match our records."

**Comment by 24aitor** [comment]
Did you run php artisan make:auth? Can you login from /login view? Don't forget to add your user email to superadmin keys on config

**Comment by onubrooks** [comment]
thanks for the reply, i actually made a mistake when creating a user with tinker and not hashing the password so that was the issue.

**Comment by ConsoleTVs** [comment]
You're welcome :)
