### ISSUE TITLE
Protect route by role

### ISSUE THREAD

**Issue by nexxai** [Laralum/Laralum#14]
I've looked through the documentation but I can't seem to exactly figure out how I'd limit a route (or more specifically, a bunch of routes)'s access to a certain role in LaraLum.  We've built out several administrator-like roles and permissions and there are some pages that we'd like to restrict only to those users.  

I'm sure this is probably super simple and when I see the answer I'm going to smack myself, but I'm still fairly new to Laravel so I'm not quite sure what the right way to do this is.

Can someone give me a hand?

**Comment by 24aitor** [comment]
Well you can define your own policies, or use directly laralum functions at the start of the route function.

Check the [authorization documentation](https://laralum.com/docs/Users/Usage).

**Comment by ConsoleTVs** [comment]
Using ```Laralum\Users\Models\User``` that edtends the ```App\User```,  you can use a function HasRole to determine of a user have a specified role, you can make this check in either a policy, a controller or in a middleware. Here's the api page: https://laralum.com/docs/Roles/API
