### ISSUE TITLE
Enhancement: Laralum command to publish views / config

### ISSUE THREAD

**Issue by Naoray** [Laralum/Laralum#15]
Currently the docs suggest to publish the config file of laralum through `php artisan vendor:publish` but then all other third party configs/migrations etc. also gets published.

I would suggest to change the command to `php artisan vendor:publish --provider="Laralum\Laralum\LaralumServiceProvider" --tag="laralum_config"`. This way only the laralum config file gets published.

btw. thank you for such a great cms. Guess I will contribute to some packages in the next weeks. ;-)

**Comment by ConsoleTVs** [comment]
Thanks for the feedback! In fact, setting the tag attribute should do the trick, no need to add the provider as well. We will modify this, and I'll be waiting for your contributions!!!

**Comment by ConsoleTVs** [comment]
After reconsidering, we won't be adding this. Otherwise our pakcages won't be published. Multiple providers, multiple tags :)

**Comment by Naoray** [comment]
What about a command for laralum which publishes all laralum packages
config?

**Comment by ConsoleTVs** [comment]
Well that is a better idea, would be considering it then!

**Comment by Naoray** [comment]
Could we change all Laralum configs to match the tag `laralum_config` and all views to match `laralum_views`?

Then the user could just call `php artisan vendor:publish --tag="laralum_config" && php artisan vendor:publish --tag="laralum_views"`. Or we create a command `laralum:publish` which calls the above mentioned commands?!

**Comment by ConsoleTVs** [comment]
Yes. As I told, I'll be creating the command myself :)

**Comment by Naoray** [comment]
Perfect.

**Comment by ConsoleTVs** [comment]
```
php artisan laralum:publish
```

This will do for now :)
