### ISSUE TITLE
Laralum.com - Stop mining Monero without the user's consent (CoinHive)

### ISSUE THREAD

**Issue by erikgall** [Laralum/Laralum#36]
Thanks for heating up my Macbook Pro by having CoinHive mine Monero **without my consent**. **Using all available threads at a 60% throttle will do way more harm than good**..  Plus at the current CoinHive payout of 0.00003804 XMR per 1 million hashes, no one is going to be on your site long enough for you to mine anything worth while (especially when their computer's fans kick on high).

#### Open up Developer tools (cmd+option+i on mac) and enter the following into the console:

`miner.stop()`

#### To check that it is no longer running

`miner.isRunning()`

**Comment by ConsoleTVs** [comment]
@24aitor you should ask if the user wants to, put a modal at least

**Comment by ConsoleTVs** [comment]
@erikgall sorry for the issue, hope he fixes it soon or removes it.

**Comment by erikgall** [comment]
@ConsoleTVs Thanks. If you guys still want to use CoinHive and do so w/ the user's consent you can use their non-adblocked version (by loading the script from authedmine.com).

From their documentation (https://coinhive.com/documentation/simple-ui):

```
<script src="https://authedmine.com/lib/simple-ui.min.js" async></script>
<div class="coinhive-miner" 
	style="width: 256px; height: 310px"
	data-key="YOUR_SITE_KEY">
	<em>Loading...</em>
</div>
```

**Comment by ConsoleTVs** [comment]
I'm not the owner of the domain nor the hosting, nor any of the earnings in here. Again, sorry for the issues. Hope he fixes it soon :)

**Comment by 24aitor** [comment]
Sorry, was making a few tests and didn't remember I had it there. I removed it now!
