### ISSUE TITLE
Documentation url not working

### ISSUE THREAD

**Issue by euperia** [Laralum/Laralum#38]
Documentation domain name is not working - needs renewing?  

https://laralum.com shows connection refused
http://laralum.com/ shows domain holding page.

**Comment by euperia** [comment]
Thanks.

**Comment by euperia** [comment]
Is there anywhere I can access the documentation? Can't see a repo for it.

**Comment by 24aitor** [comment]
Sorry for for taking so long to answer, I'm very busy!

The website is working now on:

https://laralum.aitorriba.com
