### ISSUE TITLE
SuperAdmin vs. Roles

### ISSUE THREAD

**Issue by nexxai** [Laralum/Laralum#40]
I've got a question about users who are SuperAdmins vs. users who have roles.  

In several of my blade files, I have to check if the person has permission to see a certain piece of data or can view a certain button.  I'd like to do this via roles, but I can't add roles to my superAdmin account, meaning that in every place that happens, I have to do:

`@if (Auth::User()->hasPermission('site::role') || \Laralum\Users\Models\User::findOrFail(Auth::id())->superAdmin())`

Which gets really ugly after a while.  Is there a reason why hasPermission() doesn't include the superAdmins by default?  Or if not, is there a way that I can modify it to do so?

**Comment by ConsoleTVs** [comment]
Would this work for you?

https://github.com/Laralum/Roles/pull/8/files

will be reduced to:

```php
@if (Auth::User()->hasPermission('site::role', true)
```

**Comment by nexxai** [comment]
In theory, that would work, but since the "true" doesn't really feel obvious as to what's being considered "true", I was thinking more of a setting in config/laralum.php that you could just turn on for the whole site, vs. having to denote it each time. 

In that file we list

```
    'superadmins' => [
        'my@email.here',
    ],
```

Maybe something like:

```
    'superadmin_has_all_roles' => [
        'true'
    ],
```
and then the HasRolesAndPermissions.php would check that setting and return true if it's set?  If I was better at programming, I'd submit a PR, but I still don't understand how checking stuff like that works.

**Comment by ConsoleTVs** [comment]
It's alright, we take care of it, give me a minute

**Comment by ConsoleTVs** [comment]
Update to laralum 1.3.0 and roles 1.1.0.

You'll have to manually update your config to set the default value to true (simply add this option to your laralum.php config file):

https://github.com/Laralum/Laralum/blob/master/config/laralum.php#L34

**Comment by nexxai** [comment]
Yep, that's perfect!  I just submitted a small PR because the HasRolesAndPermissions.php was missing an apostrophe, but yeah, this is exactly what I was looking for.  Thank you so much!

**Comment by ConsoleTVs** [comment]
Happy to hear that, it's fixed now, thanks!
