### ISSUE TITLE
Include Assets rather than GitCDN

### ISSUE THREAD

**Issue by Braunson** [Laralum/Laralum#5]
I noticed in https://github.com/Laralum/Laralum/blob/master/src/Views/layouts/master.blade.php that it directly links to `gitcdn` for many of the assets, why not include this directly into the package to make it customization?

Perhaps this is already an item on your todo list 😄

**Comment by ConsoleTVs** [comment]
Hello @Braunson !

Thanks a lot for the feedback, we decided to use gitCDN to avoid unessesary fiels and commands to be copied, including the mlocally would require a publish and in fact, when the assets gets updated they get kinda messy.

On the other hard, customization is still posible and will be expanded, using:

https://laralum.com/docs/Customization/Description

It still needs much development but as far as I'm concerned, I think it can do everything you'll like it to do!
