### ISSUE TITLE
PHP 7+ Requirement

### ISSUE THREAD

**Issue by tricki** [Laralum/Laralum#6]
Because the required package `ConsoleTVs/Identify` is using a [PHP return type declaration](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.return-type-declarations) Laralum currently only works on PHP 7+.

I already [created an issue](https://github.com/ConsoleTVs/Identify/issues/1) in the repo but I thought I should mention it here as well.

I ran into a problem when I tried running `php artisan migrate` during the installation. I got the following error:

```
 [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected ':', expecting ';' or '{'
```

To temporarily fix it until the package is updated remove all return type declarations in the following files:

- vendor/consoletvs/identify/src/Identify.php
- vendor/consoletvs/identify/src/IdentifyServiceProvider.php
- vendor/consoletvs/identify/src/Facades/IdentityFacade.php

**Comment by ConsoleTVs** [comment]
Hello! Woah, will check it rin an hour! Give us a second chance!

**Comment by ConsoleTVs** [comment]
Fixed, thanks for pointing it out!
