### ISSUE TITLE
syntax error, unexpected ':', expecting ';' or '{'

### ISSUE THREAD

**Issue by Sndan** [Laralum/Laralum#8]
after doing 
php artisan migrate

this error pop ups

  [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected ':', expecting ';' or '{'

fresh laravel installation

**Comment by ConsoleTVs** [comment]
Hello, please tell us the file where this error occurs, this is mostly on the first line of the debug :)

Laravel & php version ?

**Comment by Sndan** [comment]
Laravel 5.4 php 7
After I add the provider class and do the migration it gives me that issue of removed ..All will be ok

**Comment by 24aitor** [comment]
We suppose that you created well the database with collation utf8mb4 and setup your .env properly, no?

**Comment by Sndan** [comment]
Database is connected and migrate ...Users added ...Laravel is working

**Comment by ConsoleTVs** [comment]
Hello, please tell us the file where this error occurs, this is mostly on the first line of the debug :)

We need to know WHERE this line of code is located ^^

**Comment by Sndan** [comment]
this is the problem ! I want to know what is wrong and where ... this is all what I get

C:\xampp\htdocs\laralums>php artisan migrate

  [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected ':', expecting ';' or '{'

**Comment by ConsoleTVs** [comment]
Are you using the latest version of our packages?


Does this fix the issue?

```
composer update
php artisan migrate
```

**Comment by eusonlito** [comment]
@sndan, can you paste the error stored in `storage/logs/laravel-XXX.log` file?

**Comment by Sndan** [comment]
I was busy with the work today ... just had some free time .....
Èrik,,
not sure what was the issue but after I run composer update.

**Comment by ConsoleTVs** [comment]
You're welcome :)
