### ISSUE TITLE
Call to a member function connection() on null

### ISSUE THREAD

**Issue by casidos** [Laralum/Laralum#9]
Following the instructions for a fresh installation,

I got this error when I try to publish the views.

`php artisan vendor:publish`

`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function connection() on null`

On the Site I got this Laravel Error:

`FatalThrowableError in Model.php line 1016:
Call to a member function connection() on null`

**Comment by 24aitor** [comment]
Can you give more info about this error or share a photo to know if it's a laralum bug and at where part of publishing process it occur? Whats your php version?

**Comment by ConsoleTVs** [comment]
Are you using any auth provider rather than laravel one? Is your database connected correctly? Did you migrate first?

Eloquent should be enabled in any case.

**Comment by casidos** [comment]
I just follow the instructions.

I´m using the Auth by Laravel and runnign with Laragon.

![2017-04-26 21_10_34-tobyquiniela dev](https://cloud.githubusercontent.com/assets/5394612/25464950/f4165900-2ac4-11e7-8afb-f1cb8a34080e.png)

**Comment by ConsoleTVs** [comment]
Can you create a test route and use a simple model inside to see if its working?

routes/web.php

```
Route::get("/test", function(){
    return \App\User::all():
})
```

You should see a json with all the users or an empty json array if no users are found.

If you see the same error there's an error in your laravel app.

Have you tried updating the library?

```
composer update
php artisan migrate
```

**Comment by casidos** [comment]
After perform the 

`composer update`

I receive the following error and I can't use **php artisan tinker** for example.

![2017-04-27 20_26_06-cmder](https://cloud.githubusercontent.com/assets/5394612/25510914/285327f6-2b89-11e7-8d93-1853aa7ba54e.png)

**Comment by 24aitor** [comment]
You need to configure your database connection on laravel first, check ur settings on the .env
